### ISSUE TITLE
fastecdsa for c

### ISSUE THREAD

**Issue by hamnaz** [AntonKueltz/fastecdsa#41]
Dear dev
if you have fastecdsa for c implmentation, it would be great, or reffer link simlar ecdsa in c 
bc python fastecdsa slow in multiple works, or you can update it by applying python gmpy2 for fast processing
waiting your updates and refrences
regards

**Comment by AntonKueltz** [comment]
You can always pull the C code directly out of the `src/` directory and use it as you like, this code is in the public domain so you're free to use and modify it as you see fit. That being said there's more established C libs (like `openssl`) that are better reviewed and implement very specific ECC optimizations that are probably better to use. The main reason they aren't used here was to provide an implementation that wasn't dependent on huge C libraries that can be non-trivial to install and keep updated (though GMP still raises its own issues when on Windows).

Going to close the issue since there's no plans to turn this into a C lib, feel free to follow up with any comments though.
