### ISSUE TITLE
Is it possible for this to be used with Micropython?

### ISSUE THREAD

**Issue by TGiles1998** [AntonKueltz/fastecdsa#83]
Hi,

Looking to use ECDSA with micropython. Do you think this would be feasible with this library?

Many thanks,

Thomas

**Comment by AntonKueltz** [comment]
Hi Thomas,

I'm unfamiliar with micropython. A cursory glance indicates it's implemented in C, but I don't know how well it works with C extensions and third party C libraries. You'll have to see if you can install GMP on the host, and if building the project works. It might be easier to clone the repo and try `python setup.py install` to install rather than using pip, as you might have more luck debugging that way.

**Comment by TGiles1998** [comment]
Hi,
Many thanks for your reply. I will implement your suggestions and get back to you.

Thomas

**Comment by AntonKueltz** [comment]
I'm going to close this issue, feel free to reopen it if there are any follow on questions or discussion.
